### ISSUE TITLE
BuildStage error - incorrect reference to Jenkinsfile

### ISSUE THREAD

**Issue by sujikann** [manheim/terraform-pipeline#168]
Error: groovy.lang.MissingPropertyException: No such property: Jenkinsflie for class: BuildStage
Cause: Incorrect property name for Jenkinsfile

https://github.com/manheim/terraform-pipeline/blob/53974cbfbc79d200e3fd04d21ba64ecfe65df5e7/src/BuildStage.groovy#L32

**Comment by kmanning** [comment]
Released in v5.2 - https://github.com/manheim/terraform-pipeline/releases/tag/v5.2
