### ISSUE TITLE
ConditionalApplyPlugin: Allow 'apply' on branches for specific environments

### ISSUE THREAD

**Issue by boommies** [manheim/terraform-pipeline#172]
**Use Case:**
I want to be able to apply changes to non-production environments, without merging to master.

Example: I have 3  environments: 
* qa
* uat
* prod

I want to be able to make a feature branch in git, and apply the changes from that branch to qa, before merging it into uat and prod.

**Example Code:** 
```
@Library(['terraform-pipeline']) _

Jenkinsfile.init(this)

ConditionalApplyPlugin.withBranchApplyEnabledFor('qa').init()

def validate = new TerraformValidateStage()
def deployQa = new TerraformEnvironmentStage('qa')
def deployUat = new TerraformEnvironmentStage('uat')
def deployProd = new TerraformEnvironmentStage('prod')

validate.then(deployQa)
        .then(deployUat)
        .then(deployProd)
        .build()
```

**Expected:** 

When I create a git branch and push a change, the pipeline will:
1. Run a terraform plan for  'qa'
2. Allow the user to apply the plan to 'qa'
3. Run a plan for 'uat' (*DOES NOT* allow apply for 'uat')
4. Run a plan for 'prod' (*DOES NOT* allow apply for 'uat')

**Comment by boommies** [comment]
Alternative to above:

When I create a git branch and push a change, the pipeline will:

1. Run a plan for 'qa'
2. Run a plan for 'uat'
3. Run a plan for 'prod'
4. Allow the user to apply the plan for 'qa' (only at the end)

**Comment by ChrisBubelisCAI** [comment]
I like the first approach, with the subtle change that it is driven by the creation of a pull request and commits to that pull request branch.

**Comment by kmanning** [comment]
In hindsight, I think option 1 is the most easily implemented as well.  Cool, let's set that as the goal for this issue.

**Comment by kmanning** [comment]
Bumping to a future release

**Comment by kmanning** [comment]
Bumping to a future release

**Comment by kmanning** [comment]
bumping to a future release

**Comment by kmanning** [comment]
Related: https://github.com/manheim/terraform-pipeline/issues/328 - this issue would allow `apply` across all environments on some branches.

**Comment by kmanning** [comment]
Given the similarity between issue #172 and #328, it feels like we should change the suggested method names in the example code above.  What if: 

For Issue #172: apply on branches for some environments
```
.withApplyOnEnvironment('qa')
```

For Issue #328: 
```
.withApplyOnBranch('master')
```

**Comment by kmanning** [comment]
Issues #25 and #172 are related.  I wonder if the code examples should be changed to reflect the relationship.  Consider the following: 

Issue #25 - allow apply on specific *branches*
```
ConditionalApplyPlugin.withApplyOnBranch('master')
```

Issue #172 - allow apply on specific *branches*
```
ConditionalApplyPlugin.withApplyOnEnvironment('qa')
```
