### ISSUE TITLE
Support Applying a tfvar file to all environments.

### ISSUE THREAD

**Issue by dkolb** [manheim/terraform-pipeline#194]
We store some lists of IP addresses currently in files, example: `ip_whitelist.auto.tfvars` in order to include those values across all of our environments.  While this works well, it also means those files need to live in the root of our repository instead of in the tfvars subdirectory.  It also means there's a bit of black magic for anyone looking at our job logs, so it'd be nice to have them explicitly included via a `-var-file` argument for the Jenkins logs.

**Comment by kmanning** [comment]
Merged into v5.5-dev
