### ISSUE TITLE
Support Terraform Landscape - coinbase/terraform-landscape

### ISSUE THREAD

**Issue by vincentclee** [manheim/terraform-pipeline#210]
Terraform Landscape is a tool for reformatting the output of `terraform plan` to be easier to read and understand.

https://github.com/coinbase/terraform-landscape

### Before
<img src="https://raw.githubusercontent.com/coinbase/terraform-landscape/master/doc/before.png" width="65%" alt="Original Terraform plan output" />

### After
<img src="https://github.com/coinbase/terraform-landscape/raw/master/doc/after.png" width="65%" alt="Improved Terraform plan output" />

**Comment by kmanning** [comment]
Sample Code:

* One-time setup:
    * terraform-landscape gem is pre-installed and available on your shell path

```
// Jenkinsfile
@Library(['terraform-pipeline@v3.10']) _

Jenkinsfile.init(this, env)

TerraformLandscapeGemPlugin.init() // Use the terraform-landscape gem to format plans

def validate = new TerraformValidateStage()

// Plans should be formatted with terraform-landscape gem
def deployQA = new TerraformEnvironmentStage('qa')
def deployUat = new TerraformEnvironmentStage('uat')
def deployProd = new TerraformEnvironmentStage('prod')

validate.then(deployQa)
        .then(deployUat)
        .then(deployProd)
        .build()
```
