### ISSUE TITLE
AgentNode Support with PR Plugin

### ISSUE THREAD

**Issue by bondezbond** [manheim/terraform-pipeline#230]
With the current PR plugin. AgentNode doesn't have support for Terraform Landscape since it uses hashicorp default image. To add that ability we need to be able to build dockerfiles in plugin and pass in build parameters. Thoughts on the update would be something like this

```
....
def terraformVersion = TerraformPlugin.checkVersion()
AgentNodePlugin.withAgentDockerImage("terraform-ruby:${terraformVersion}", true)
               .withAgentDockerBuildOptions("--build-arg TERRAFORM_VERSION=${terraformVersion}")
               .withAgentDockerImageOptions("--entrypoint=''")
               .init()
....
```

**Comment by bondezbond** [comment]
`AgentNodePlugin.withAgentDockerImage` will take two parameters. The first will be the image name and second will be a `true/false` parameter to build from dockerfile or pull image

**Comment by kmanning** [comment]
Related to #193
