### ISSUE TITLE
TerraformPlanResultsPR breaks with TerraformDirectoryPlugin

### ISSUE THREAD

**Issue by bondezbond** [manheim/terraform-pipeline#232]
When using TerraformPlanResultsPR with TerraformDirectoryPlugin. The corresponding terraform commands are broken and out of order and plan returns an exit code of 0.

Sample Jenkinsfile

```
@Library(['terraform-pipeline']) _

Jenkinsfile.init(this)
CredentialsPlugin.withBuildCredentials([usernameVariable: 'FOO', passwordVariable: 'GITHUB_TOKEN'], 'creds_id').init()

AnsiColorPlugin.init()
TerraformPlanResultsPR.withRepoHost("https://enterprise.github.com/api/v3/")
                      .withRepoSlug("ORG/REPO_NAME")
                      .withGithubTokenEnvVar("GITHUB_TOKEN")
                      .init()

TerraformDirectoryPlugin.withDirectory('./infrastructure/').init()
TfvarsFilesPlugin.withDirectory('./infrastructure/tfvars').init()

def terraformVersion = TerraformPlugin.checkVersion()
AgentNodePlugin.withAgentDockerImage("hashicorp/terraform:${terraformVersion}")
               .withAgentDockerImageOptions("--entrypoint=''")
               .init()

def deployDev = new TerraformEnvironmentStage('Dev')

deployDev.build()
```

The corresponding PR plan is this

```
terraform plan '-input=false' '-var-file=./infrastructure/tfvars/dev.tfvars' ./infrastructure/ '-out=tfplan'
```

notice the directory `infrastructure` is before `out=tfplan`

**Comment by bondezbond** [comment]
this might be an issue with `TerraformDirectoryPlugin` actually

**Comment by bondezbond** [comment]
the issue is actually here.

https://github.com/manheim/terraform-pipeline/blob/master/src/TerraformPlanCommand.groovy#L53-L58

`TerraformPlanResultsPR` using withSuffixes that adds additional terraform parameters which it wasn't designed for that additional. We might have to make an separate way of adding additional terraform parameters instead

**Comment by kmanning** [comment]
Related to #193
