### ISSUE TITLE
ConditionalApplyPlugin - allow apply on specific branches

### ISSUE THREAD

**Issue by kmanning** [manheim/terraform-pipeline#25]
* Allow the branch (master) to be customized
* (REMOVING disable - See Issue #329 )

**Comment by kemper** [comment]
For allowing this plugin to be disabled, I take that to mean always apply? I can update my changes to support that. One option is to take an empty list of branches to mean "all"

```
ConditionalApplyPlugin.withBranchApplyEnabledFor([])
```

or an extra option:

```
ConditionalApplyPlugin.withBranchApplyEnabledFor([], all: true)
```

or a wildcard:

```
ConditionalApplyPlugin.withBranchApplyEnabledFor(['*'])
```

or I can add a new method and new field for controlling enable/disable.

```
ConditionalApplyPlugin.setEnabled(false)
```

**Comment by kmanning** [comment]
Let's split  this issue into 2 - they are distinct.   I  updated the  original post

**Comment by kmanning** [comment]
Issues #25 and #172 are related.  I wonder if the code examples should be changed to reflect the relationship.  Consider the following: 

Issue #25 - allow apply on specific *branches*
```
ConditionalApplyPlugin.withApplyOnBranch('master')
```

Issue #172 - allow apply on specific *branches*
```
ConditionalApplyPlugin.withApplyOnEnvironment('qa')
```

**Comment by kemper** [comment]
Sounds good to me. Current the name/parameter combination on the PR is `withBranchApplyEnabledFor(['branch1', 'branch2')` . Do you want me to rename and change the params to be varargs?

**Comment by kmanning** [comment]
Yes on the rename.

On the varargs, it feels friendlier.  So yes, I'd personally appreciate it, unless there's a good reason not to.
