### ISSUE TITLE
Provide a hook for arbitrary scripts after 'apply'

### ISSUE THREAD

**Issue by kmanning** [manheim/terraform-pipeline#250]
UseCase: Healthcheck
* I've deployed infrastructure to an environment, using terraform-pipeline
* I want to confirm that the infrastructure "works as expected"
* If I had a "hook" that allowed me to run an arbitrary shell script, my shell script could validate the my infrastructure "works as expected"
* If my shell script returns a zero-status, I assume "it works" (based on unix return code conventions)
* If my shell script returns a non-zero status, I assume that "it did not work as expected", and marks the "apply" stage of my environment as failed.  I'm not  allowed to continue.
* My shell script should get all the "goodness" of pipelines that operate during "apply".  Eg: I can access the IAM role and EnvironmentVariables provided by plugins like ParameterStorePlugin.

**Comment by kmanning** [comment]
UseCase: Database migrations
* I've deployed a database using terraform-pipeline
* I'd like to run a database migration, to ensure that my database schema is altered in an automated fashion, and all my environments are kept in-sync.
* If my shell script returns a zero-status, I assume "it works" (based on unix return code conventions)
* If my shell script returns a non-zero status, I assume that "it did not work as expected", and marks the "apply" stage of my environment as failed. I'm not allowed to continue.
* My shell script should get all the "goodness" of pipelines that operate during "apply". Eg: I can access the IAM role and EnvironmentVariables provided by plugins like ParameterStorePlugin.

**Comment by kmanning** [comment]
Other thoughts: 
- This could potentially be a hook for ChangeMangement tasks

**Comment by kmanning** [comment]
HealthCheck Script
```
@Library(['terraform-pipeline@v5.1']) _

Jenkinsfile.init(this)
PostApplyPlugin.run('./bin/healthcheck.sh')

def validate = new TerraformValidateStage()
def deployQa = new TerraformEnvironmentStage('qa')
def deployUat = new TerraformEnvironmentStage('uat')
def deployProd = new TerraformEnvironmentStage('prod')

validate.then(deployQa)
        .then(deployUat)
        .then(deployProd)
        .build()
```

DatabaseMigrate Script
```
@Library(['terraform-pipeline@v5.1']) _

Jenkinsfile.init(this)
PostApplyPlugin.run('./bin/run_migrations.sh')

def validate = new TerraformValidateStage()
def deployQa = new TerraformEnvironmentStage('qa')
def deployUat = new TerraformEnvironmentStage('uat')
def deployProd = new TerraformEnvironmentStage('prod')

validate.then(deployQa)
        .then(deployUat)
        .then(deployProd)
        .build()
```

**Comment by kmanning** [comment]
bumping to a future release

**Comment by jantman** [comment]
I've taken a crack at an implementation for this in #319
