### ISSUE TITLE
Question: override variables in plan

### ISSUE THREAD

**Issue by anupam16s** [manheim/terraform-pipeline#252]
Can we override variables in terraform plan from jenkinsfile?
For example: Canary deployment with weighted targets.

**Comment by kmanning** [comment]
Yes.  The way that we've done it on our teams is to store the weights externally, then pass them in as environment variables.  You can pass in any variable to terraform, by prefixing the name of the variable with `TF_VAR_` - See: https://www.terraform.io/docs/commands/environment-variables.html

terraform-pipeline offers a few different plugins, to retrieve values from an external store, and then convert them to environment variables.  See: https://github.com/manheim/terraform-pipeline#credentials-and-configuration-management.  Eg: We've stored record weights in ParameterStore, and adjusted the weights and redeployed environments to shift traffic in a controlled fashion.

To put everything together more concretely:
1.  Your terraform code could define a variable with a default weight.  That variable would be used to set the weight value for a Route53 record.  `variable ROUTE_53_WEIGHT { type = String }`
2.  Your terraform-pipeline could use any plugin that will inject environment variables.  In this example, I'll use ParameterStoreBuildWrapperPlugin.  In ParameterStore, I'd create a key/value pair `TF_VAR_ROUTE_53_WEIGHT`, and set it to my desired weight for the environment that I want to deploy.
3. I'd run terraform.  ParameterStoreBuildWrapper will set an environment variable `TF_VAR_ROUTE_53_WEIGHT=<weight>`, and terraform-plan/terraform-apply will automatically set that value for the terraform variable `ROUTE_53_WEIGHT` in my code.

**Comment by anupam16s** [comment]
Thank you @kmanning
