### ISSUE TITLE
Getting error RejectedAccessException with TFvarplugin

### ISSUE THREAD

**Issue by anupam16s** [manheim/terraform-pipeline#253]
Hi,
I am using TFVarplugin and getting below error. Pipeline working ok without this plugin.
I tried with v5.3, v5.5,v5.8-dev.
Error: org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: 

Can you please suggest. If I need to update any config in my jenkinsfile or shall I use any other branch.

**Comment by kmanning** [comment]
Can you share the Jenkinsfile code that your using?  Or the stack trace?

**Comment by kmanning** [comment]
If needed, please reopen this issue with a copy of the Jenkinsfile that you're using.
