### ISSUE TITLE
Remove CRQ Plugin

### ISSUE THREAD

**Issue by kmanning** [manheim/terraform-pipeline#283]
* This plugin is manheim-specific.  Remove it from this library, and push it to a separate library.

**Comment by jleopold28** [comment]
@kmanning Are will still planning on removing the CRQ plugin?

**Comment by kmanning** [comment]
Yes.  If it needs to stick around, there's a separate internal project that it can live in, and be pulled in as a separate library.

**Comment by jantman** [comment]
@kmanning This plugin leverages an internal Manheim tool (``manheim_remedy``) that's deprecated. We're getting increasing internal pressure from the teams that manage the backend systems that tool connects to, to deprecate it ASAP. We have an internal replacement for it, the jenkins-crq library.

What's needed from me/us to get some more momentum behind this issue?

**Comment by kmanning** [comment]
PR's are welcome.  I don't think this should be originally been added to the library, and the replacement using the jenkins-crq library is already available in an internally.

I think a PR to simply remove this plugin all together would be appropriate.
