### ISSUE TITLE
Support Global ParameterStore path for all stages

### ISSUE THREAD

**Issue by bondezbond** [manheim/terraform-pipeline#299]
So instead of duplicating certain values for each environment stage example NewRelic, Datadog, Pagerduty api keys. It might be beneficial to add a Global ParameterStore option when the plugin is initiated.

**Example**
```
ParameterStoreBuildWrapperPlugin.globalParameter('<path1>')
                                .globalParameter('<path2>')
                                .init()
```

**Comment by kmanning** [comment]
Neat, I could see that being a useful feature.  To clarify, `<path1>`, `<path2>` would be exact parameters, and the values of those exact parameters would be added across every environment,  yes?

**Comment by bondezbond** [comment]
I wanted to expose `naming` option as well. So we can leverage that as well from the plugin

**Comment by kmanning** [comment]
Can you clarify what you mean by exposing the  naming function, and how  that might work with  this new feature?

**Comment by bondezbond** [comment]
So ParameterStoreWrapper has a bunch of options so I'm thinking we support
```
ParameterStoreBuildWrapperPlugin.globalParameter('/new_relic/', [ recursive: true, naming: 'relative' ] )
                                .init()
```

We can pass an array of options as a second argument
