### ISSUE TITLE
Fix Version Detection: whitespace not trimmed

### ISSUE THREAD

**Issue by bondezbond** [manheim/terraform-pipeline#300]
It looks like when consolidating we removed version trimming. Before the `readFile` function read the file and removed whitespace. Should we add that logic back OR maybe document it in the release?
  
https://github.com/manheim/terraform-pipeline/blob/a5270f657f11e8374caab324b0c002c4219eab69/src/TerraformPlugin.groovy#L33

**Comment by kmanning** [comment]
Whomp.  I think that broke during a refactor.  The readFile method was getting  copy pasted everywhere, and I'm trying to consolidate it into Jenkinsfile.  https://github.com/manheim/terraform-pipeline/blob/master/src/Jenkinsfile.groovy#L120-L127

**Comment by bondezbond** [comment]
hmm based on that it should be trimming it. Let me see if I can find the issue.

**Comment by kmanning** [comment]
Here's the PR that refactored the code and broke the Plugin - https://github.com/manheim/terraform-pipeline/pull/298/files#diff-2724a09cdd048285c15140f07b77fb5dR33
