### ISSUE TITLE
Add the ability to specify terraform-pipeline starting execution workspace directory

### ISSUE THREAD

**Issue by vincentclee** [manheim/terraform-pipeline#309]
Currently, we have the **TerraformDirectoryPlugin** which allows **terraform-pipeline** to do this:

```
TerraformDirectoryPlugin.withDirectory("app1/terraform").init()
```
```
terraform <command> app1/terraform
...
```

What i would like **terraform-pipeline** to support:

```
TerraformStartingDirectoryPlugin.withDirectory("appQ/terraform").init()

```
```
cd appQ/terraform
terraform <command> .
```

##

This is important with monolithic pipeline repo's where the `.terraform-version` flat file is only read from the root of the project tree when using the **TerraformDirectoryPlugin**.

**Comment by kmanning** [comment]
Seems like a good UseCase.  In thinking through this, we'll have to be careful about how other TerraformCommandPlugins interact with this new UseCase.  Lots of plugins decorate the front of the command (eg: awssume/parameter-store-exec), and the command itself is treated as a single shell step.  What you're looking for is a separate shell step.

**Comment by kmanning** [comment]
I don't know that TerraformDirectoryPlugin is so inappropriately named for this UseCase.  I wonder if it could offer both behaviors with the same plugin? 

```
TerraformDirectoryPlugin.withDirectory("app1/terraform").init()
```
vs 
```
TerraformDirectoryPlugin.withStartDirectory("app1/terraform").init()
```
or something like
```
TerraformDirectoryPlugin.withDirectory("app1/terraform").withCdCommand().init()
```

**Comment by vincentclee** [comment]
I like option one.
Extend **TerraformDirectoryPlugin** to support the `withStartDirectory` method

**Comment by kmanning** [comment]
Note: Change in terraform 0.14 and 0.15 related to subdirectories.  https://www.terraform.io/docs/cli/commands/plan.html#passing-a-different-configuration-directory

**Comment by vincentclee** [comment]
bump

**Comment by vincentclee** [comment]
This is officially needed on terraform 0.15 and later.

**Comment by kdibenedetto** [comment]
Yeah, I went to use tf 1.0.1 and was hit with this issue.
