### ISSUE TITLE
Lock the git commit between pipeline stages

### ISSUE THREAD

**Issue by kmanning** [manheim/terraform-pipeline#31]
* One a pipeline kicks off, the git commit hash should be captured and reused for every check of every step of that pipeline run.
* Prove that this is a requirement. Prove that it breaks without locking the git commit hash.

**Comment by jantman** [comment]
This might be naive, but doesn't Multi-Branch Pipeline already do this?

**Comment by kmanning** [comment]
Yes.  I think I posted this before we confirmed.
