### ISSUE TITLE
[FEATURE] - updated default confirm message to contain environment

### ISSUE THREAD

**Issue by bondezbond** [manheim/terraform-pipeline#318]
I know we can override it but I think it would be nice if we can updated the Confirm and Delete stages to have the environment in the comment

https://github.com/manheim/terraform-pipeline/blob/f80fbe16cdf79a5511ca4b5f1f234dad24601ec6/src/ConfirmApplyPlugin.groovy#L9

`Are you absolutely sure the plan above is correct, and should be IMMEDIATELY DEPLOYED via "terraform apply" on stage ${environment}?`

thoughts?

**Comment by kmanning** [comment]
I like it
