### ISSUE TITLE
Defect: GithubPRPlanPlugin - failing plan marked as success?

### ISSUE THREAD

**Issue by kmanning** [manheim/terraform-pipeline#320]
* Investigate this

**Comment by CliffJumper** [comment]
Not sure if this is the same, but with v5.14, I'm seeing terraform plan errors "swallowed".  The net effect is that I don't see the plan output in the Jenkins log.

**Comment by kmanning** [comment]
How to reproduce: 
1. Create a terraform resource that will fail on `terraform plan`.  For example, read from a file that does not exist.
2. Enable the GithubPRPlanPlugin in your pipeline - this will pipeline the output to `plan.out`, and stderr to `plan.err`
3. Run your pipeline
4. Expected: The pipeline should fail at the end of the plan command, and the error message from terraform plan should be displayed.
5. Actual: The pipeline continues.  The stderr output goes unused in the `plan.err` file
