### ISSUE TITLE
Publish v5.16 Release

### ISSUE THREAD

**Issue by kmanning** [manheim/terraform-pipeline#374]
- [x] update CHANGELOG
- [x] push any open issues to next release
- [ ] publish/release tag

**Comment by bondezbond** [comment]
Should we add a messages about start using `ConditionalApplyPlugin.withApplyOnBranch('main')` in the release notes? Thats `master` by default will be deprecated

**Comment by bondezbond** [comment]
I was thinking something like this.

To support the wide diversity of technology community. We will be default the branch to `main` vs `master` in release **v16**. You can start working `main` as your new branch now by implementing `ConditionalApplyPlugin.withApplyOnBranch('main')` plugin. This way users can work out any issues of a branch name change

**Comment by kmanning** [comment]
I already published the Release, so I can't change the CHANGELOG, but I added a Deprecated section to the ReleaseNotes on github.  What do you think?  https://github.com/manheim/terraform-pipeline/releases/tag/v5.16

**Comment by bondezbond** [comment]
I'll add it the CHANGELOG in the next release
