### ISSUE TITLE
Bug: PassPlanPlugin & GithubPRPlugin

### ISSUE THREAD

**Issue by bondezbond** [manheim/terraform-pipeline#386]
When using both using both these plugins. The terraform apply fails depending on the order you init the plugins. To be able to use both these plugins you have to set PassPlanPlugin ~AFTER~ BEFORE GithubPRPlugin.

The PR part still works in this order as well. Not sure why the GithubPRPlugin is output `tfplan`. Maybe we should remove that part of the code?

https://github.com/manheim/terraform-pipeline/blob/3fcca23dce9a746b455e3ddf74d8508e0f5e5ab2/src/GithubPRPlanPlugin.groovy#L42

**Comment by bondezbond** [comment]
Looking at the history of the code seems like it was used for landscape. I believe its safe to remove it.

**Comment by kmanning** [comment]
Can you outline the defect/tests in a little more detail?  IE: If I had to reproduce the things that you'd test, what would I have to do?

__Example:__

Scenario 1: Test Plugins together, A/B
1. Minimal pipeline code snippet that I could run
2. Expected behavior

Scenario 2: Test Plugins together, reverse order B/A
1. Minimal pipeline code snippet that I could run
2. Expected behavior

Scenario 3: Test Plugin A Only
1. Minimal pipeline code snippet that I could run
2. Expected behavior

Scenario 4: Test Plugin B Only
1. Minimal pipeline code snippet that I could run
2. Expected behavior

**Comment by bondezbond** [comment]
## Scenario 1
When GithubPR plugin is enabled first and then PassPlan is enabled second, 
  1. only one -out=tfplan-{env} should be set as argument
  2. Terraform plan should post back Github PR as a comment
  3. When merged main branch should apply stashed -out=tfplan-{env}

```
        CredentialsPlugin.withBuildCredentials([usernameVariable: 'FOO', passwordVariable: 'GITHUB_TOKEN'], 'ghe_man_vikings_pat').init()
        GithubPRPlanPlugin.init()
        PassPlanFilePlugin.init()
```

Current status: 
  1. Plan stashes tfplan-{env}
  2. PR jobs posts a plan output to comment.
  3. Apply tries to unstash tfplan-{env}, Jenkins errors out saying it can not find the tfplan-{env} and failed to extract `tfplan-{env}.tar.gz`

## Scenario 2
When GithubPR plugin is enabled second and then PassPlan is enabled first, 
```
        CredentialsPlugin.withBuildCredentials([usernameVariable: 'FOO', passwordVariable: 'GITHUB_TOKEN'], 'ghe_man_vikings_pat').init()
        PassPlanFilePlugin.init()
        GithubPRPlanPlugin.init()
```
  1. Only one -out=tfplan-{env} should be set as argument
  2. Terraform plan should post back Github PR as a comment
  3. When merged main branch should apply stashed -out=tfplan-{env}.

Current status: Plan stashes tfplan-{env}, 
  1. Plan stashes tfplan-{env}
  2. PR jobs posts a plan output to comment.
  3. Terraform apply does not apply tfplan-{env}

## Scenario 3
When GithubPR plugin is enabled

1. terraform plan should **not** be setting argument -out=tfplan

```
        CredentialsPlugin.withBuildCredentials([usernameVariable: 'FOO', passwordVariable: 'GITHUB_TOKEN'], 'ghe_man_vikings_pat').init()
        GithubPRPlanPlugin.init()
```

Current status terraform plan has -out=tfplan

## Scenario 4
When PassPlan plugin is enabled

1. terraform plan should be setting argument -out=tfplan-{env}

```
        CredentialsPlugin.withBuildCredentials([usernameVariable: 'FOO', passwordVariable: 'GITHUB_TOKEN'], 'ghe_man_vikings_pat').init()
        GithubPRPlanPlugin.init()
```

Current status:

  1. Plan stashes tfplan-{env}
  3. Apply tries to unstash tfplan-{env}, Jenkins errors out saying it can not find the tfplan-{env} and failed to extract `tfplan-{env}.tar.gz`

**Comment by kmanning** [comment]
Scenario 4's example should be: 
```
CredentialsPlugin.withBuildCredentials([usernameVariable: 'FOO', passwordVariable: 'GITHUB_TOKEN'], 'ghe_man_vikings_pat').init()
PassPlanFilePlugin.init()
```
right?

**Comment by bondezbond** [comment]
Sorry fixed that. It should just be

```
PassPlanFilePlugin.init()
```
